### ISSUE TITLE
random results on OTB

### ISSUE THREAD

**Issue by TOT-BENCHMARK** [IlchaeJung/RT-MDNet#11]
I tried several sequences of otb, but the results of each run are different.

0 Bird1 : 0.201098956064 , total mIoU:0.201098956064, fps:27.1192838431
1 Box : 0.302790951364 , total mIoU:0.251944953714, fps:34.7540858495
2 Couple : 0.662352476224 , total mIoU:0.388747461218, fps:37.7562471058
3 Freeman4 : 0.666170731107 , total mIoU:0.45810327869, fps:39.7685989323
4 BlurBody : 0.722626621854 , total mIoU:0.511007947323, fps:39.1456625614
5 Jumping : 0.678226531945 , total mIoU:0.538877711426, fps:41.4720706029

0 Bird1 : 0.111411426274 , total mIoU:0.111411426274, fps:15.230079837
1 Box : 0.699401980322 , total mIoU:0.405406703298, fps:27.8460658587
2 Couple : 0.682630547749 , total mIoU:0.497814651448, fps:33.7325697033
3 Freeman4 : 0.611166113115 , total mIoU:0.526152516865, fps:36.3247190875
4 BlurBody : 0.718198220241 , total mIoU:0.56456165754, fps:36.3292326732
5 Jumping : 0.676521638398 , total mIoU:0.58322165435, fps:38.9468761315

**Comment by IlchaeJung** [comment]
Thank you for your interests.

This is the characteristics of stochastic algorithms. In Deep learning based approach like MDNet, TCNN, RT-MDNet, etc, we stochastically draw samples many times for estimate, update. Therefore, for every trials, the results may be different from each other. However, in our algorithm, the variance of success rate is within 0.02~0.03. Therefore, if you obtain 0.632 as a score of SR, you can obtain the score from paper in additional trial. Thank you :)

**Comment by TOT-BENCHMARK** [comment]
Thank you for your reply.
