### ISSUE TITLE
the results of OTB2015,fix random seeds

### ISSUE THREAD

**Issue by TOT-BENCHMARK** [IlchaeJung/RT-MDNet#12]
I didn't change any parameters. Because of the randomness of the tracking results, I fixed the random seeds. But the final result is lower than that shown in the paper. What's the matter?
The result of the code I run is PR=0.847，SR=0.632.

**Comment by IlchaeJung** [comment]
Thank you for your interests.

I answered your problem in the previous issue. Thank you :)
