### ISSUE TITLE
About  receptive_field

### ISSUE THREAD

**Issue by xi-mao** [IlchaeJung/RT-MDNet#16]
rois[:, 0] *= cur_resize_ratio[0]
    rois[:, 1] *= cur_resize_ratio[1]
    rois[:, 2] = np.maximum(rois[:,0]+1,rois[:, 2]*cur_resize_ratio[0] - receptive_field)
    rois[:, 3] = np.maximum(rois[:,1]+1,rois[:, 3]*cur_resize_ratio[1] - receptive_field)

I have question about receptiive_field, why there rois[:, 2]*cur_resize_ratio[0]  minus receptive_field?  what's the meaning about receptive_field？ can anyone answer me?

**Comment by weizhaowang** [comment]
have u understood it now?i have the same question as u

**Comment by 1329844541** [comment]
QQ:1329844541,I want to deep communicate with you.Thank you!
