### ISSUE TITLE
about the randomness

### ISSUE THREAD

**Issue by lawpdas** [IlchaeJung/RT-MDNet#20]
I think that the randomness only comes from `SampleGenerator`, and only `np.rand` is used in  `SampleGenerator`. I have fixed the random seed of numpy, random and pytorch. But I cannot get the same result on the same video. 
I really wonder where the randomness comes from.

**Comment by IlchaeJung** [comment]
There is randomness lines on Run.py . 
You can un-comment that lines. 
However, If  you fix the random seed, the evaluation results on the benchmark will be little bit different from the results on the paper. 
Thank you.
