### ISSUE TITLE
How  to start？

### ISSUE THREAD

**Issue by 1329844541** [IlchaeJung/RT-MDNet#4]
1.Where put pretrained model ？You instruction is too siample to understand.
  
put it on'./modules'

**Comment by 1329844541** [comment]
2.python version？
python2，Torch 0.4

**Comment by 1329844541** [comment]
Traceback (most recent call last):
  File "/home/mou/桌面/RT-MDNet/Run.py", line 3, in <module>
    from tracker import *
  File "/home/mou/桌面/RT-MDNet/tracker.py", line 15, in <module>
    from data_prov import *
  File "./modules/data_prov.py", line 18, in <module>
    from img_cropper import *
  File "./modules/img_cropper.py", line 3, in <module>
    from roi_align.modules.roi_align import RoIAlign
  File "./modules/roi_align/modules/roi_align.py", line 3, in <module>
    from ..functions.roi_align import RoIAlignFunction, RoIAlignAdaFunction, RoIAlignDenseAdaFunction
  File "./modules/roi_align/functions/roi_align.py", line 3, in <module>
    from .._ext import roi_align
  File "./modules/roi_align/_ext/roi_align/__init__.py", line 2, in <module>
    from torch.utils.ffi import _wrap_function
  File "/home/mou/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

Can you tell me in 'from tracker import *'  what is '*'means?

**Comment by 1329844541** [comment]
3.
0 FleetFace : 0.635385444018 , total mIoU:0.635385444018, fps:22.0188454495
1 Shaking : 0.755609686754 , total mIoU:0.695497565386, fps:20.5078921637
2 Gym : 0.476123071148 , total mIoU:0.622372733973, fps:20.4322087473
3 Singer2 : 0.491590633797 , total mIoU:0.589677208929, fps:20.115665847
4 Bolt2 : 0.626244696313 , total mIoU:0.596990706406, fps:20.3388576366
5 Bird2 : 0.765128736236 , total mIoU:0.625013711378, fps:19.2077135761
6 Car1 : 0.671785363338 , total mIoU:0.631695375943, fps:20.3129399589
7 Baby_ce : 0.713131735255 , total mIoU:0.641874920857, fps:20.1544710035
8 Dog1 : 0.78856894409 , total mIoU:0.658174256772, fps:21.1052713055
9 Football1 : 0.696766076618 , total mIoU:0.662033438757, fps:20.5379553207
10 Dancer : 0.681762785744 , total mIoU:0.663827015756, fps:20.7942835601
11 Jumping : 0.680227512105 , total mIoU:0.665193723785, fps:21.0043458547
Traceback (most recent call last):
  File "/home/mou/RT-MDNet/Run.py", line 117, in <module>
    img_list,gt=genConfig(seq_path,opts['set_type'])
  File "/home/mou/RT-MDNet/Run.py", line 38, in genConfig
    gt = np.loadtxt(seq_path + '/groundtruth_rect.txt', delimiter=',')
  File "/home/mou/anaconda2/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1092, in loadtxt
    for x in read_data(_loadtxt_chunksize):
  File "/home/mou/anaconda2/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1019, in read_data
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "/home/mou/anaconda2/lib/python2.7/site-packages/numpy/lib/npyio.py", line 738, in floatconv
    return float(x)
ValueError: invalid literal for float(): 226 38 196 366 
How to solution?

**Comment by 1329844541** [comment]
python2，Torch 0.4

**Comment by IlchaeJung** [comment]
> 0 FleetFace : 0.635385444018 , total mIoU:0.635385444018, fps:22.0188454495
> 1 Shaking : 0.755609686754 , total mIoU:0.695497565386, fps:20.5078921637
> 2 Gym : 0.476123071148 , total mIoU:0.622372733973, fps:20.4322087473
> 3 Singer2 : 0.491590633797 , total mIoU:0.589677208929, fps:20.115665847
> 4 Bolt2 : 0.626244696313 , total mIoU:0.596990706406, fps:20.3388576366
> 5 Bird2 : 0.765128736236 , total mIoU:0.625013711378, fps:19.2077135761
> 6 Car1 : 0.671785363338 , total mIoU:0.631695375943, fps:20.3129399589
> 7 Baby_ce : 0.713131735255 , total mIoU:0.641874920857, fps:20.1544710035
> 8 Dog1 : 0.78856894409 , total mIoU:0.658174256772, fps:21.1052713055
> 9 Football1 : 0.696766076618 , total mIoU:0.662033438757, fps:20.5379553207
> 10 Dancer : 0.681762785744 , total mIoU:0.663827015756, fps:20.7942835601
> 11 Jumping : 0.680227512105 , total mIoU:0.665193723785, fps:21.0043458547
> Traceback (most recent call last):
> File "/home/mou/RT-MDNet/Run.py", line 117, in 
> img_list,gt=genConfig(seq_path,opts['set_type'])
> File "/home/mou/RT-MDNet/Run.py", line 38, in genConfig
> gt = np.loadtxt(seq_path + '/groundtruth_rect.txt', delimiter=',')
> File "/home/mou/anaconda2/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1092, in loadtxt
> for x in read_data(_loadtxt_chunksize):
> File "/home/mou/anaconda2/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1019, in read_data
> items = [conv(val) for (conv, val) in zip(converters, vals)]
> File "/home/mou/anaconda2/lib/python2.7/site-packages/numpy/lib/npyio.py", line 738, in floatconv
> return float(x)
> ValueError: invalid literal for float(): 226 38 196 366
> How to solution?

Umm.. sorry, I haven't observe that error before. Maybe, it is a problem related to python version or needs more exception codes to our implementation. If so, please give me your solution. Thank you.

**Comment by 1329844541** [comment]
Thank you for your kindness.I mat this problem when I put a new sequence to test RT-MDNet.The data format "226 38 196 366" is illegal,I change "226 38 196 366" to "266,38,196,366".
