### ISSUE TITLE
bb_result and bb_result_nobb 

### ISSUE THREAD

**Issue by 1329844541** [IlchaeJung/RT-MDNet#6]
I transfor 'result.npy' to'result.mat',found .mat file has' bb_result' and 'bb_result_nobb ',what does those result maens? Can you help me to learn more information,I just really interested in it.

**Comment by IlchaeJung** [comment]
> I transfor 'result.npy' to'result.mat',found .mat file has' bb_result' and 'bb_result_nobb ',what does those result maens? Can you help me to learn more information,I just really interested in it.

Thank you for your interest. Simply, bb_result is our result with boundingbox regression while bb_result_nobb means our result without boundingbox regression.

**Comment by 1329844541** [comment]
Thank you.

**Comment by 1329844541** [comment]
Thank you.
