### ISSUE TITLE
The results of OTB2015

### ISSUE THREAD

**Issue by yangkai12** [IlchaeJung/RT-MDNet#9]
Thank you for releasing this excellent work.
I tested your model on OTB2015 and the result was 0.632,This result is lower than 0.650 in your paper. I use the default parameter settings of your code. Could you please tell me how to solve this issue? Thank you very much.

**Comment by xi-mao** [comment]
> Thank you for releasing this excellent work.
> I tested your model on OTB2015 and the result was 0.632,This result is lower than 0.650 in your paper. I use the default parameter settings of your code. Could you please tell me how to solve this issue? Thank you very much.

Hello， did you solve the problem？ I also got 0.633 in OTB2015
